draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: true
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: ''
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    "tabler": "https://unpkg.com/@tabler/icons/icons/outline/{}.svg"
    "mdi": "https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg"
    "mdil": "https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg"
    "material": "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg"
    "phosphor": "https://unpkg.com/@phosphor-icons/core/assets/{}.svg"
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&BRACES': '[]'
    '&PREV': '$_'
    '&URL': '[.]'
    '&URL': '[.]'
    '&kp LS(EQUAL)': '='
    '&kp LS(AMPERSAND)': '&'
    '&kp LS(AT_SIGN)': '@'
    '&kp LS(UNDERSCORE)': '_'
    '&kp LS(LEFT_PARENTHESIS)': '('
    '&kp LS(RIGHT_PARENTHESIS)': ')'
    '&kp LS(PERCENT)': '%'
    '&hold_tap LG(LS(S)) SQT': {tap: "'", hold: 'SCRNSHOT'}
    '&num_word': 'NUMWORD'
    '&msc SCRL_LEFT': Scroll Left
    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&mmv MOVE_UP': Mouse ↑
    '&mmv MOVE_DOWN': Mouse ↓
    '&mmv MOVE_LEFT': Mouse ←
    '&mmv MOVE_RIGHT': Mouse →
    '&msc SCRL_UP': Scroll ↑
    '&msc SCRL_DOWN': Scroll ↓
    '&msc SCRL_LEFT': Scroll ←
    '&msc SCRL_RIGHT': Scroll →
    '&mkp LCLK': Left Click
    '&kp UP': ↑
    '&kp DOWN': ↓
    '&kp LEFT_ARROW': ←
    '&kp RIGHT': →
    '&kp PAGE_UP': Page ↑
    '&kp PAGE_DOWN': Page ↓
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click
        # Modifiers
    'LCTRL': "$$mdi:apple-keyboard-control$$"
    'LALT': "$$mdi:apple-keyboard-option$$"
    'LSHIFT': "$$mdi:apple-keyboard-shift$$"
    'LSHFT': "$$mdi:apple-keyboard-shift$$"
    'LGUI': "$$mdi:apple-keyboard-command$$"
    '&kp LG(Q)': "$$mdi:apple-keyboard-command$$+Q"
    'RCTRL': "$$mdi:apple-keyboard-control$$"
    'RALT': "$$mdi:apple-keyboard-option$$"
    'RSHIFT': "$$mdi:apple-keyboard-shift$$"
    'RSHFT': "$$mdi:apple-keyboard-shift$$"
    'RGUI': "$$mdi:apple-keyboard-command$$"
    'LS(LC(LALT))': "$$mdi:triangle$$" # Meh
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    LEFT_SHIFT: 'Shift'
    RIGHT_SHIFT: 'Shift'
    LEFT_GUI: 'GUI'
    RIGHT_GUI: 'GUI'
    LEFT_ALT: 'ALT'
    RIGHT_ALT: 'ALT'
    LCTRL: 'CTRL'
    RCTRL: 'CTRL'
  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []

